HST_FactionTemplate {
 m_sTemplateId "fia_resistance"
 m_sFactionKey "FIA"
 m_sDisplayName "FIA Resistance"
 m_bPlayable 1
 m_aCapabilities {
  "infantry"
  "light_vehicles"
  "hideouts"
  "weapon_caches"
  "air_support_unlockable"
 }
 m_aInfantryPrefabs {
  "{84B40583F4D1B7A3}Prefabs/Characters/Factions/INDFOR/FIA/Character_FIA_Rifleman.et"
  "{45A02CA25CBA9443}Prefabs/Characters/Factions/INDFOR/FIA/Character_FIA_Medic.et"
  "{58E47E5A4D599432}Prefabs/Characters/Factions/INDFOR/FIA/Character_FIA_MG.et"
  "{C77DFB8546B3F2A2}Prefabs/Characters/Factions/INDFOR/FIA/Character_FIA_LAT.et"
 }
 m_aVehiclePrefabs {
  "{16C1F16C9B053801}Prefabs/Vehicles/Wheeled/Ural4320/Ural4320_transport.et"
  "{0B4DEA8078B78A9B}Prefabs/Vehicles/Wheeled/UAZ469/UAZ469_PKM.et"
 }
 m_aGroupPrefabs {
  "{CE41AF625D05D0F0}Prefabs/Groups/INDFOR/Group_FIA_RifleSquad.et"
  "{5BEA04939D148B1D}Prefabs/Groups/INDFOR/Group_FIA_FireTeam.et"
 }
 m_aPatrolGroupPrefabs {
  "{6E725D44CA973C24}Prefabs/Groups/INDFOR/Group_FIA_SentryTeam.et"
  "{5BEA04939D148B1D}Prefabs/Groups/INDFOR/Group_FIA_FireTeam.et"
 }
 m_aQRFGroupPrefabs {
  "{CE41AF625D05D0F0}Prefabs/Groups/INDFOR/Group_FIA_RifleSquad.et"
  "{22F33D3EC8F281AB}Prefabs/Groups/INDFOR/Group_FIA_MachineGunTeam.et"
 }
 m_aSupportIds {
  "support_mortar"
 }
}
