HST_FactionTemplate {
 m_sTemplateId "rhs_usmc_occupier"
 m_sFactionKey "RHS_USAF"
 m_sDisplayName "RHS USMC Occupiers"
 m_aCapabilities {
  "infantry"
  "light_vehicles"
  "armored_vehicles"
  "helicopters"
  "qrf"
 }
}

