HST_FactionTemplate {
 m_sTemplateId "rhs_afrf_invader"
 m_sFactionKey "RHS_AFRF"
 m_sDisplayName "RHS AFRF Invaders"
 m_aCapabilities {
  "infantry"
  "light_vehicles"
 "armored_vehicles"
 "helicopters"
 "qrf"
 }
 m_aGroupPrefabs {
  "{A6A3EDA237E3D336}Prefabs/Groups/OPFOR/RHS_AFRF/MSV/VKPO_Summer/AmbientPatrols/Group_RHS_RF_MSV_VKPO_S_FireGroup_NotSpawned.et"
  "{D9523F26504A8D59}Prefabs/Groups/OPFOR/RHS_AFRF/SPEC/VVRG/Group_RHS_hSPEC_VVRG_TEAM.et"
 }
 m_aPatrolGroupPrefabs {
  "{A6A3EDA237E3D336}Prefabs/Groups/OPFOR/RHS_AFRF/MSV/VKPO_Summer/AmbientPatrols/Group_RHS_RF_MSV_VKPO_S_FireGroup_NotSpawned.et"
 }
 m_aQRFGroupPrefabs {
  "{D9523F26504A8D59}Prefabs/Groups/OPFOR/RHS_AFRF/SPEC/VVRG/Group_RHS_hSPEC_VVRG_TEAM.et"
  "{622DDA327B669B67}Prefabs/Groups/OPFOR/RHS_AFRF/SPEC/SSO/Group_RHS_hSPEC_SSO_ATTeam.et"
 }
}
