HST_FactionTemplate {
 m_sTemplateId "rhs_afrf_invader"
 m_sFactionKey "RHS_AFRF"
 m_sDisplayName "RHS AFRF Invaders"
 m_aCapabilities {
  "infantry"
  "light_vehicles"
  "armored_vehicles"
  "helicopters"
  "qrf"
 }
}

