HST_CampaignPreset {
 m_sPresetId "rhs_everon"
 m_sDisplayName "h-istasi Everon: FIA vs USMC vs AFRF"
 m_sResistanceFactionKey "FIA"
 m_sOccupierFactionKey "RHS_USAF"
 m_sInvaderFactionKey "RHS_AFRF"
 m_sBalanceConfig "Configs/HST/Balance/HST_CE311_Balance.conf"
 m_sMapDefinition "Configs/HST/Maps/HST_Everon.conf"
 m_sMissionRegistry "Configs/HST/Missions/HST_CE311_Missions.conf"
 m_aUnavailableCapabilities {
  "fixed_wing_aircraft"
  "sead"
  "artillery"
 }
}

