enum HST_ECampaignPhase
{
	HST_CAMPAIGN_SETUP,
	HST_CAMPAIGN_ACTIVE,
	HST_CAMPAIGN_WON,
	HST_CAMPAIGN_LOST
}

enum HST_EZoneType
{
	HST_ZONE_TOWN,
	HST_ZONE_OUTPOST,
	HST_ZONE_RESOURCE,
	HST_ZONE_FACTORY,
	HST_ZONE_RADIO_TOWER,
	HST_ZONE_AIRFIELD,
	HST_ZONE_SEAPORT,
	HST_ZONE_POLICE_STATION,
	HST_ZONE_BANK,
	HST_ZONE_HIDEOUT,
	HST_ZONE_MISSION_SITE
}

enum HST_EMissionCategory
{
	HST_MISSION_ASSASSINATION,
	HST_MISSION_CONQUEST,
	HST_MISSION_CONVOY,
	HST_MISSION_DESTROY,
	HST_MISSION_LOGISTICS,
	HST_MISSION_RESCUE,
	HST_MISSION_DYNAMIC,
	HST_MISSION_SUPPORT
}

enum HST_EMissionStatus
{
	HST_MISSION_AVAILABLE,
	HST_MISSION_ACTIVE,
	HST_MISSION_SUCCEEDED,
	HST_MISSION_FAILED,
	HST_MISSION_EXPIRED
}

